### ISSUE TITLE
Error during docker-compose up 

### ISSUE THREAD

**Issue by peterleary** [MG-RAST/Skyport2#41]
Hi guys, 

I'm trying to get Skyport2 going, but I'm running into the following error during `docker-compose up`: 

`ERROR: manifest for mgrast/awe-monitor:latest not found`

It's all on a fresh install of macOS 10.14.1, with a fresh Docker install (so I hopefully haven't broken anything!)

Any suggestions welcome, and thanks in advance,
Peter

**Comment by wgerlach** [comment]
Hi Peter,
this specific issue was temporary and and has been fixed by now. There are right now one or two other bugs I introduced recently and I am in the process of fixing them. I let you know when it should work again. Sorry for the inconvenience!
Wolfgang

**Comment by wgerlach** [comment]
Hi Peter,

everything should work now. Sorry for the delay, I had to rewrite some code in AWE and missed to reference a stable version in this repository. Let me know if you still have problems.
